name: ncc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: planningcenter/ncc-build@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        src: 'index.js'
